server:
  port: 8080

spring:
  application:
    name: dynamic-task-scheduler
  
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  task:
    scheduling:
      pool:
        size: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,scheduledtasks
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.taskscheduler: DEBUG
    org.springframework.scheduling: DEBUG
