server:
  port: 8080

spring:
  application:
    name: task-scheduler-day24
  
  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  threads:
    virtual:
      enabled: true

# Task Scheduler Configuration
task-scheduler:
  pool-size: 10
  retry:
    max-attempts: 3
    base-delay-ms: 1000
    max-delay-ms: 30000
    exponential-multiplier: 2.0
    jitter-factor: 0.1
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.taskscheduler: DEBUG
    org.springframework.scheduling: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
