apiVersion: v2
name: task-scheduler
description: A Helm chart for Task Scheduler with Redis and PostgreSQL
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 13.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
