version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    
  app1:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SERVER_PORT=8080
      - SPRING_REDIS_HOST=redis
      - COORDINATION_LEADER_ELECTION_CANDIDATE_ID=app1-${RANDOM}
    volumes:
      - ../ui:/app/ui
      
  app2:
    build: ..
    ports:
      - "8081:8080"
    depends_on:
      - redis
    environment:
      - SERVER_PORT=8080
      - SPRING_REDIS_HOST=redis
      - COORDINATION_LEADER_ELECTION_CANDIDATE_ID=app2-${RANDOM}
    volumes:
      - ../ui:/app/ui
      
  app3:
    build: ..
    ports:
      - "8082:8080"
    depends_on:
      - redis
    environment:
      - SERVER_PORT=8080
      - SPRING_REDIS_HOST=redis
      - COORDINATION_LEADER_ELECTION_CANDIDATE_ID=app3-${RANDOM}
    volumes:
      - ../ui:/app/ui
