version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: task-scheduler-postgres
    environment:
      POSTGRES_DB: taskscheduler
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskscheduler"]
      interval: 10s
      timeout: 5s
      retries: 5

  task-scheduler-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: task-scheduler-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/tasks/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
