server:
  port: 8080

spring:
  application:
    name: optimistic-lock-scheduler
    
  threads:
    virtual:
      enabled: true
      
  datasource:
    url: jdbc:h2:mem:scheduler;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        
  h2:
    console:
      enabled: true
      path: /h2-console
      
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
      
scheduler:
  task:
    processor:
      threads: 10
      retry:
        max-attempts: 3
        delay-ms: 100
        multiplier: 2.0
        
logging:
  level:
    com.scheduler: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate.SQL: DEBUG
