version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scheduler1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/scheduler
      - SPRING_DATASOURCE_USERNAME=scheduler
      - SPRING_DATASOURCE_PASSWORD=scheduler123
      - SCHEDULER_INSTANCE_ID=docker-scheduler-1
    depends_on:
      - postgres

  scheduler2:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/scheduler
      - SPRING_DATASOURCE_USERNAME=scheduler
      - SPRING_DATASOURCE_PASSWORD=scheduler123
      - SCHEDULER_INSTANCE_ID=docker-scheduler-2
    depends_on:
      - postgres

  scheduler3:
    build: .
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/scheduler
      - SPRING_DATASOURCE_USERNAME=scheduler
      - SPRING_DATASOURCE_PASSWORD=scheduler123
      - SCHEDULER_INSTANCE_ID=docker-scheduler-3
    depends_on:
      - postgres

volumes:
  postgres_data:
