spring:
  datasource:
    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9095
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        web-port: 8080

# Docker-specific logging
logging:
  level:
    com.taskscheduler: DEBUG
    org.springframework.retry: DEBUG
    org.springframework.boot.autoconfigure.h2: DEBUG
