spring:
  application:
    name: spring-retry-task-scheduler
  
  datasource:
    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Custom retry configuration
app:
  retry:
    email-service:
      max-attempts: 3
      initial-delay: 1000
      multiplier: 2.0
      max-delay: 5000
    
    database:
      max-attempts: 5
      initial-delay: 500
      multiplier: 1.5
      max-delay: 3000
    
    external-api:
      max-attempts: 4
      initial-delay: 2000
      multiplier: 2.0
      max-delay: 10000

logging:
  level:
    com.taskscheduler: DEBUG
    org.springframework.retry: DEBUG
