version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskscheduler-postgres
    environment:
      POSTGRES_DB: taskscheduler
      POSTGRES_USER: taskscheduler
      POSTGRES_PASSWORD: taskscheduler123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - taskscheduler-network

  adminer:
    image: adminer:4.8.1
    container_name: taskscheduler-adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - taskscheduler-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  taskscheduler-network:
    driver: bridge
