server:
  port: 8080

spring:
  application:
    name: thread-pool-scheduler
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,scheduledtasks,threaddump,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.taskscheduler: DEBUG
    org.springframework.scheduling: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

task:
  scheduler:
    pool-size: 10
    max-pool-size: 20
    thread-name-prefix: "custom-scheduler-"
    await-termination-seconds: 20
    wait-for-tasks-to-complete-on-shutdown: true
