server:
  port: 8080

spring:
  application:
    name: distributed-task-scheduler
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:scheduler;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,scheduledtasks
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

# Custom Scheduler Configuration
scheduler:
  enabled: true
  pool-size: 10
  leader-election:
    enabled: true
  distributed-lock:
    enabled: true
    default-lock-time: PT30M
  task-discovery:
    interval: PT30S

# Logging
logging:
  level:
    com.scheduler: DEBUG
    net.javacrumbs.shedlock: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{instanceId}] %logger{36} - %msg%n"
