spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: 6379

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.scheduler: INFO
